# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    init: >
      echo 'install modules' &&
      pip --upgrade pip
    command: pip instal -r requirements.txt
  - name: Test
    init: >
      echo 'install pytest' &&
      pip install pytest
    command: pytest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
