# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    command: >
      echo 'install modules' &&
      pip --upgrade pip &&
      pip instal -r requirements.txt
  - name: Test
    command: >
      echo 'install pytest' &&
      pip install pytest &&
      pytest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
